name: flutter_task_planner_app

description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  table_calendar: ^2.2.3
  shared_preferences: ^0.5.8
  sqflite: ^1.3.1
  path: 1.6.4
  flutter_picker: ^1.1.5
  analog_clock: ^0.0.1
  font_awesome_flutter: ^8.5.0
  form_bloc: ^0.5.1
  flutter_form_bloc: ^0.4.2
  flutter_bloc: ^0.21.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  